version: '3.1'

services:
  ubuntu-dev:
    build:
      context: .
      dockerfile: ubuntu/Dockerfile
    user: ${CURRENT_UID}
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.git:/root/.git
      - ../:/root/workspace
    ports:
      - 1234:1234
    command: tail -f /dev/null
